"""Pydantic models for TMF641 resources."""

from app.models.common import (
    AppointmentRef,
    Characteristic,
    Note,
    Place,
    RelatedParty,
    ResourceRef,
    ServiceOrderItemRelationship,
    ServiceOrderRelationship,
    ServiceRef,
    ServiceRelationship,
    ServiceSpecificationRef,
    TargetServiceSchema,
    TMFEntity,
)
from app.models.enums import (
    ServiceOrderActionType,
    ServiceOrderItemStateType,
    ServiceOrderStateType,
    ServiceStateType,
)
from app.models.hub import Hub, HubCreate, HubRef
from app.models.notifications import (
    ServiceOrderAttributeValueChangeNotification,
    ServiceOrderCreateNotification,
    ServiceOrderDeleteNotification,
    ServiceOrderEvent,
    ServiceOrderNotification,
    ServiceOrderStateChangeNotification,
)
from app.models.service_order import (
    ServiceOrder,
    ServiceOrderCreate,
    ServiceOrderCreateResponse,
    ServiceOrderItem,
    ServiceOrderItemCreate,
    ServiceOrderItemPatch,
    ServiceOrderPatch,
    ServiceOrderPatchResponse,
    ServiceRestriction,
)

__all__ = [
    "AppointmentRef",
    "Characteristic",
    "Note",
    "Place",
    "RelatedParty",
    "ResourceRef",
    "Hub",
    "HubCreate",
    "HubRef",
    "ServiceOrderActionType",
    "ServiceOrderAttributeValueChangeNotification",
    "ServiceOrderCreate",
    "ServiceOrderCreateNotification",
    "ServiceOrderCreateResponse",
    "ServiceOrderDeleteNotification",
    "ServiceOrderEvent",
    "ServiceOrderItem",
    "ServiceOrderItemCreate",
    "ServiceOrderItemStateType",
    "ServiceOrderItemRelationship",
    "ServiceOrderItemPatch",
    "ServiceOrderNotification",
    "ServiceOrderPatch",
    "ServiceOrderPatchResponse",
    "ServiceOrder",
    "ServiceOrderRelationship",
    "ServiceOrderStateChangeNotification",
    "ServiceOrderStateType",
    "ServiceRestriction",
    "ServiceRef",
    "ServiceRelationship",
    "ServiceSpecificationRef",
    "ServiceStateType",
    "TMFEntity",
    "TargetServiceSchema",
]

